# fly.toml app configuration file generated for study4as-website on 2024-10-02T22:31:58-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'study4as-website'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
